### ISSUE TITLE
Feature: User-can-search-for-recipes

### ISSUE THREAD

**Issue by adrienne-yung** [adrienne-yung/ajax-project2#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User-can-search-for-recipes

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Access a search bar on the main page to search recipes

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![ajaxfeature1](https://user-images.githubusercontent.com/90871776/142259459-4f53baab-7125-45a9-8d91-353ec191d73a.png)

![ajaxfeature1 2](https://user-images.githubusercontent.com/90871776/142259483-7e1c6c74-eaf7-4dad-a5e6-7436b1be0009.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] In your _index.html_, create a layout for the contents of your homepage
- [ ] Add **form** w/ type **text** and create a submit **button**
- [ ] In your _styles.css_ and apply the main background to your homepage. 
- [ ] Style your html contents, search bar input, and your submit button
- [ ] In your _main.js_, XMLHttpRequest Edamam API to retrieve the information you need
- [ ] query select your search bar and create an **addEventListener** for your search bar.
- [ ] Create another function that displays the data you want to grab 
- [ ] In your **addEventListener** function, call on the function you've just created so that the string of what you want is filtered towards your search and have it return the list of data that user is searching for
- [ ] Create another **addEventListener** for your submit **button**
- [ ] Create a **view swapping** function so user can see different pages and navigate around the web app.
- [ ] Upon clicking the submit **button**, a function that sends user to a page that directs them to a list that only contains string value of their search (already **filter**ed)
- [ ] Make sure that click targets are either `**<a>**` or `**<button>**` elements.
- [ ] Make sure that all click targets show a **`cursor: pointer`** when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
