### ISSUE TITLE
Feature: User-can-view-a-recipe

### ISSUE THREAD

**Issue by adrienne-yung** [adrienne-yung/ajax-project2#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User-can-view-a-recipe
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon clicking on a recipe, you will be redirected to a page that shows your desired recipe that contains the information: picture of recipe, ingredients for dish, a link to recipe instructions, and nutritional facts of the recipe. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![ajaxfeature2](https://user-images.githubusercontent.com/90871776/142266847-9df054db-1f67-4385-b67d-d51ada8f0457.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] In your _index.html_, create a different data-view that shows how your search results should look like 
- [ ] In your _main.js_, create a **DOM Tree** that showcases how you want your individual recipe entry input data to look like in your html 
- [ ] Create an **addEventListener** **'click'** whenever you click on an entry
- [ ] Assign the desired data-view for each entry and send the user to that link upon click
- [ ] In your _index.html_, create a different data-view that showcases how each recipe would look like. 
- [ ] In your _styles.css_, adjust your layout to how you want each of the created data-views to look like. 
- [ ] Create an **addEventListener** **'click'** on the **button** labeled 'Instructions'
- [ ] Upon clicking the 'Instructions' **button**, user will be directed to a recipe link provided by the API
- [ ] Make sure that click targets are either **`<a>` or `<button>`** elements.
- [ ] Make sure that all click targets show a **`cursor: pointer`** when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
