### ISSUE TITLE
Feature: User-can-view-later-a-recipe 

### ISSUE THREAD

**Issue by adrienne-yung** [adrienne-yung/ajax-project2#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User-can-view-later-a-recipe
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On your desired recipe page, you will be able to select the "view later" star icon be able to access your "view later" recipes on the homepage
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![ajaxfeature3](https://user-images.githubusercontent.com/90871776/142268971-e11c5c42-1452-4996-ba5a-f810f2394ca9.png)
![ajaxfeature3 2](https://user-images.githubusercontent.com/90871776/142271065-b39b0761-da8b-4795-b762-1abb4aa43506.png)
![ajaxfeature3 3](https://user-images.githubusercontent.com/90871776/142271086-430bb241-c665-493b-aa44-d1d493661015.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] In your _index.html_, add your View Later & Favorite icon
- [ ] In your _styles.css_, add styling for your View Later and Favorite icon, when it is active and when it is not active. 
- [ ] Create an **addEventListener** **'click'** on your View Later icon.
- [ ] Upon being clicked if the View Later icon is white, change to yellow. If clicked upon why View Later icon is yellow, change to white. 
- [ ] Create an **addEventListener** **'click'** on your Favorite icon.
- [ ] Upon being clicked if the Favorite icon is white, change to red. If clicked upon why Favorite icon is red, change to white.
- [ ] Make sure that click targets are either **`<a>` or `<button>`** elements.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
