### ISSUE TITLE
Feature: User-can-view-recipes-in-their-lists

### ISSUE THREAD

**Issue by adrienne-yung** [adrienne-yung/ajax-project2#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User-can-view-recipes-in-their-lists
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After adding recipes using the View Later and the Favorites icon, users now have access to a list with stored recipes in each corresponding lists.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![ajaxfeature4](https://user-images.githubusercontent.com/90871776/142271883-5c6aff07-2b4f-44ff-a4e1-2493b1e33532.png)
![ajaxfeature4 2](https://user-images.githubusercontent.com/90871776/142271937-95937c0c-12e9-4828-b242-f919d10bf2f0.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create an **addEventListener 'click'** on the 2 Lists for "View Later" and "Favorites" on your main page to bring users to designated updated lists.
- [ ] Create an **addEventListener 'click'** on your main page icon to bring users to the main page. 
- [ ] In your index.html, create a different data view for "View Later" and "Favorites" list
- [ ] In your styles.css, style your "View Later" and "Favorites" list
- [ ] In your "View Later" and "Favorites" list, make sure each recipe entry found in each list takes you to desired entry. 
- [ ] Make sure that click targets are either **`<a>` or `<button>`** elements.
- [ ] Make sure that all click targets show a **`cursor: pointer`** when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
